spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 664380857069-an94lbjo2n5hbgig4jklr33294trffmr.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile